# Generated by Django 5.1.4 on 2025-03-18 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('fact_check_status', models.CharField(blank=True, editable=False, max_length=20)),
                ('composite_score', models.FloatField(default=0.0, editable=False)),
                ('evidence', models.JSONField(blank=True, default=dict, null=True)),
                ('publish_status', models.CharField(choices=[('published', 'Published'), ('withheld', 'Withheld')], default='published', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_content', to='content_generation.generatedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('body', models.TextField(max_length=5000)),
                ('fact_check_status', models.CharField(max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('manually_overridden', models.BooleanField(default=False)),
                ('processed_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_content', to='content_processing.processedcontent')),
            ],
        ),
    ]
