# Generated by Django 5.1.4 on 2025-02-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_generation', '0002_alter_generatedcontent_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField()),
                ('tags', models.JSONField()),
                ('fact_check_status', models.CharField(editable=False, max_length=20)),
                ('composite_score', models.FloatField(default=0.0, editable=False)),
                ('publish_status', models.CharField(choices=[('published', 'Published'), ('withheld', 'Withheld')], default='published', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_content', to='content_generation.generatedcontent')),
            ],
        ),
    ]
