# Generated by Django 5.1.4 on 2025-02-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedcontent',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='processedcontent',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
