# Generated by Django 5.1.4 on 2025-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_processing', '0003_alter_publishedcontent_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedcontent',
            name='body',
            field=models.TextField(max_length=5000),
        ),
    ]
