# Generated by Django 5.1.4 on 2025-02-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_processing', '0002_alter_processedcontent_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedcontent',
            name='fact_check_status',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='PublishedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('body', models.TextField(max_length=2000)),
                ('fact_check_status', models.CharField(max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('manually_overridden', models.BooleanField(default=False)),
                ('processed_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_content', to='content_processing.processedcontent')),
            ],
        ),
    ]
