# Generated by Django 5.1.4 on 2025-02-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generation', '0003_apiprompt_remove_generatedcontent_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='title',
            field=models.CharField(max_length=999),
        ),
    ]
