# Generated by Django 5.1.4 on 2025-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_checking', '0002_rename_checked_at_factcheckresult_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcheckresult',
            name='accuracy_score',
        ),
        migrations.RemoveField(
            model_name='factcheckresult',
            name='clarity_score',
        ),
        migrations.RemoveField(
            model_name='factcheckresult',
            name='composite_score',
        ),
        migrations.RemoveField(
            model_name='factcheckresult',
            name='details',
        ),
        migrations.RemoveField(
            model_name='factcheckresult',
            name='disclosure_score',
        ),
        migrations.RemoveField(
            model_name='factcheckresult',
            name='source_score',
        ),
        migrations.AddField(
            model_name='factcheckresult',
            name='evidence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factcheckresult',
            name='textual_rating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='factcheckresult',
            name='verification_score',
            field=models.FloatField(default=0.0),
        ),
    ]
