# Generated by Django 5.1.4 on 2025-03-18 15:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content_modality.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='content_processing.publishedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to='content_modality.usersession')),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_modality.videocontent')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_likes', to='content_modality.usersession')),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content_modality.videocontent')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_shares', to='content_modality.usersession')),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content_modality.videocontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='written_content', to='content_processing.publishedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_comments', to='content_modality.usersession')),
                ('written_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_modality.writtencontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_likes', to='content_modality.usersession')),
                ('written_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content_modality.writtencontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_shares', to='content_modality.usersession')),
                ('written_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content_modality.writtencontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('content', models.TextField(max_length=5000)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='written_image_content', to='content_processing.publishedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_image_comments', to='content_modality.usersession')),
                ('written_image_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_modality.writtenimagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_image_likes', to='content_modality.usersession')),
                ('written_image_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content_modality.writtenimagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_image_shares', to='content_modality.usersession')),
                ('written_image_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content_modality.writtenimagecontent')),
            ],
        ),
    ]
