# Generated by Django 5.1.4 on 2025-03-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(help_text='Summary (20-40 words)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='content_processing.publishedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_modality.videocontent')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content_modality.videocontent')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content_modality.videocontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='written_content', to='content_processing.publishedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_modality.writtencontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content_modality.writtencontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content_modality.writtencontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('content', models.TextField(max_length=2000)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='written_image_content', to='content_processing.publishedcontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_image_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_modality.writtenimagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_image_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content_modality.writtenimagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenImageContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_image_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content_modality.writtenimagecontent')),
            ],
        ),
    ]
