# Generated by Django 5.1.4 on 2025-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_modality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='summary',
            field=models.TextField(help_text='Summary (20-40 words)', max_length=200),
        ),
    ]
