# Generated by Django 5.1.4 on 2025-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_modality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtencontent',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='writtenimagecontent',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
