# Generated by Django 5.1.4 on 2025-11-27 01:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_modality', '0002_videocontent_category_writtencontent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='summary',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='writtencontent',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='writtenimagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
