from django.db import models

class GeneratedContent(models.Model):
    title = models.CharField(max_length=255)  # Title of the generated story
    body = models.TextField()  # Main content generated by the LLM
    prompt = models.TextField()  # Narrative prompt used to generate the story
    temperature = models.FloatField()  # Randomness of generation
    token_limit = models.IntegerField()  # Maximum number of tokens for output
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp for record creation

    def __str__(self):
        return self.title
