# Generated by Django 5.1.4 on 2024-12-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('False', 'False'), ('Partially True', 'Partially True'), ('Unverified', 'Unverified')], max_length=20)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
